### ISSUE TITLE
Add goreleaser CI/CD with Homebrew integration

### ISSUE THREAD

**Issue by bbkane** [yks0000/starred-repo-toc#1]
I did this with [grabbit](https://github.com/bbkane/grabbit) and [kvcrutch](https://github.com/bbkane/kvcrutch) and it's been super nice to use and install - see https://github.com/bbkane/kvcrutch/blob/master/.goreleaser.yml

**Comment by yks0000** [comment]
As this more related to GitHub, I am have added the instructions to [use GitHub Actions ](https://github.com/yks0000/starred-repo-toc/blob/master/.github/workflows/generate-md.yml)
