### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by jxzzlfh** [yks0000/starred-repo-toc#11]
The repository that I had starred but no longer exists is also written to README.md

**Comment by yks0000** [comment]
It seems to be a bug with GitHub API 

https://github.community/t/unstar-deleted-repos/180412

**Comment by yks0000** [comment]
Added a fix. Please sync your forked repo with upstream for latest changes

https://github.com/yks0000/starred-repo-toc/commit/4c8b411984c9e4b54b8c701548f6e11242099e12
