### ISSUE TITLE
XDG config standards

### ISSUE THREAD

**Issue by bbkane** [yks0000/starred-repo-toc#3]
https://github.com/yks0000/starred-repo-toc/blob/83923a48ee364687fdf7c9b0dfdeca4985581ece/cmd/root.go#L42

it looks like the default config directory is $HOME :

From https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html :

>  $XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used. 

This avoids cluttering up the HOME directory. No biggie either way :)

**Comment by yks0000** [comment]
We don't use config file.
